name: "Basic: Github CLI Usage"

on: workflow_dispatch

permissions:
    contents: read

jobs:
    print_auth_status:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ github.token }}
        steps:
            - name: "Print Auth status"
              run: |
                  gh auth status --active
