name: "Basic: Scheduling"

on:
    schedule:
        - cron: "0 0 * * *"

jobs:
    foo_job:
        runs-on: ubuntu-latest
        name: foo_job
        steps:
            - run: |
                  echo "foo"
