name: "Basic: Hello World"

on: workflow_dispatch

jobs:
    hello_world:
        name: Hello World
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: |
                  echo "Hello World!"
