name: "Basic: Environment Variables & Secrets"

on: workflow_dispatch

env:
    REPO_SCOPED_ENV_VAR: ${{ vars.REPO_SCOPED_ENV_VAR }}
    REPO_SCOPED_SECRET: ${{ secrets.REPO_SCOPED_SECRET }}
    WORKFLOW_SCOPED_ENV_VAR: "workflow_scoped_env_var_value"

jobs:
    foo_job:
        runs-on: ubuntu-latest
        environment: dev
        env:
            ENV_SCOPED_ENV_VAR: ${{ vars.ENV_SCOPED_ENV_VAR }}
            ENV_SCOPED_SECRET: ${{ secrets.ENV_SECRET }}
            FOO_JOB_SCOPED_ENV_VAR: "foo_job_scoped_env_var_value"
        steps:
            - id: foo_step_1
              name: foo_step_1
              env:
                  FOO_STEP_1_SCOPED_ENV_VAR: "foo_step_1_scoped_env_var_value"
              run: |
                  echo "REPO_SCOPED_ENV_VAR: $REPO_SCOPED_ENV_VAR"
                  echo "REPO_SCOPED_SECRET: $REPO_SCOPED_SECRET"
                  echo "ENV_SCOPED_ENV_VAR: $ENV_SCOPED_ENV_VAR"
                  echo "ENV_SCOPED_SECRET: $ENV_SCOPED_SECRET"
                  echo "WORKFLOW_SCOPED_ENV_VAR: $WORKFLOW_SCOPED_ENV_VAR"
                  echo "FOO_JOB_SCOPED_ENV_VAR: $FOO_JOB_SCOPED_ENV_VAR"
                  echo "FOO_STEP_1_SCOPED_ENV_VAR: $FOO_STEP_1_SCOPED_ENV_VAR"

            - id: foo_step_2
              name: foo_step_2
              run: |
                  echo "REPO_SCOPED_ENV_VAR: $REPO_SCOPED_ENV_VAR"
                  echo "REPO_SCOPED_SECRET: $REPO_SCOPED_SECRET"
                  echo "ENV_SCOPED_ENV_VAR: $ENV_SCOPED_ENV_VAR"
                  echo "ENV_SCOPED_SECRET: $ENV_SCOPED_SECRET"
                  echo "WORKFLOW_SCOPED_ENV_VAR: $WORKFLOW_SCOPED_ENV_VAR"
                  echo "FOO_JOB_SCOPED_ENV_VAR: $FOO_JOB_SCOPED_ENV_VAR"
                  echo "FOO_STEP_1_SCOPED_ENV_VAR: $FOO_STEP_1_SCOPED_ENV_VAR"

    bar_job:
        runs-on: ubuntu-latest
        environment: dev
        env:
            ENV_SCOPED_ENV_VAR: ${{ vars.ENV_SCOPED_ENV_VAR }}
            ENV_SCOPED_SECRET: ${{ secrets.ENV_SECRET }}
        steps:
            - id: bar_step_1
              name: bar_step_1
              run: |
                  echo "REPO_SCOPED_ENV_VAR: $REPO_SCOPED_ENV_VAR"
                  echo "REPO_SCOPED_SECRET: $REPO_SCOPED_SECRET"
                  echo "ENV_SCOPED_ENV_VAR: $ENV_SCOPED_ENV_VAR"
                  echo "ENV_SCOPED_SECRET: $ENV_SCOPED_SECRET"
                  echo "WORKFLOW_SCOPED_ENV_VAR: $WORKFLOW_SCOPED_ENV_VAR"
                  echo "FOO_JOB_SCOPED_ENV_VAR: $FOO_JOB_SCOPED_ENV_VAR"
                  echo "FOO_STEP_1_SCOPED_ENV_VAR: $FOO_STEP_1_SCOPED_ENV_VAR"
