name: "Basic: Upload & Download"

on: workflow_dispatch

jobs:
    foo_job:
        name: Foo Job
        runs-on: ubuntu-latest
        steps:
            - name: Create file
              run: |
                  echo "Hello World!" > "hello_world.txt"
            - name: Upload file
              uses: actions/upload-artifact@v4
              with:
                  name: hello_world_artifact
                  path: ./hello_world.txt

    bar_job:
        name: Bar Job
        runs-on: ubuntu-latest
        needs: [foo_job]
        steps:
            - name: Download file
              uses: actions/download-artifact@v4
              with:
                  name: hello_world_artifact
                  path: ./
            - name: Read file
              run: |
                  cat ./hello_world.txt
